<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<fieldset>
    <legend><?php __('Antenna Information'); ?> </legend>
    
<?php

//    echo $this->Form->input('antenna_testing',
//                                    array(
//                                        'label'=>'Antenna Testing',
//                                        'type'=>'text',
//                                        'div'=>array('class'=>'formfields')
//                                    ));
    ?>
</fieldset>